version: '3.9'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Maps container's port 5000 to host's port 5000
    env_file:
      - .env  # Load environment variables from .env file
    environment:
      FLASK_ENV: development
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    command: flask run --host=0.0.0.0 --reload
